# Generated by Django 2.1.4 on 2018-12-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenderedTweetsUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
    ]
