# Generated by Django 2.1.4 on 2018-12-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenderedTweetsUI', '0003_auto_20181221_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='reply_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
